services:
  app:
    container_name: laravel_app
    build: ./docker/php
    volumes:
      - .:/var/www
    depends_on:
      - db
  nginx:
    image: nginx
    container_name: laravel_nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    image: mysql:latest
    restart: always
    container_name: laravel_db
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: "Asia/Tokyo"
    networks:
      - mysql_network

volumes:
  mysql_data:
networks:
  mysql_network:
